# Board settings.
BOARD = uno
PORT = /dev/ttyACM0
# For Arduino 1.0
PROGRAMMER = arduino

# Which header files and libraries to use
LIBS = SoftwareSerial SPI
# Which user-defined libraries to use
# By default these should appear in ~/sketchbook/libraries
CUSTOM_LIBS = RFM22

include $(HOME)/.vim/bundle/vim-arduino/templates/master.mk
